# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\add_contact.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Add_contact(object):
    def setupUi(self, Add_contact):
        Add_contact.setObjectName("Add_contact")
        Add_contact.resize(400, 600)
        Add_contact.setMinimumSize(QtCore.QSize(400, 600))
        Add_contact.setMaximumSize(QtCore.QSize(400, 600))
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Add_contact)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(Add_contact)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(Add_contact)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.pushButton = QtWidgets.QPushButton(Add_contact)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.horizontalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Add_contact)
        QtCore.QMetaObject.connectSlotsByName(Add_contact)

    def retranslateUi(self, Add_contact):
        _translate = QtCore.QCoreApplication.translate
        Add_contact.setWindowTitle(_translate("Add_contact", "Form"))
        self.label.setText(_translate("Add_contact", "Введите имя пользователя"))
        self.pushButton.setText(_translate("Add_contact", "Отправить запрос"))
