from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Client_MainWindow(object):
    def setupUi(self, Client_MainWindow):
        Client_MainWindow.setObjectName("Client_MainWindow")
        Client_MainWindow.resize(800, 600)
        Client_MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        Client_MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(Client_MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_chat = QtWidgets.QWidget()
        self.tab_chat.setObjectName("tab_chat")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_chat)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_message = QtWidgets.QLineEdit(self.tab_chat)
        self.lineEdit_message.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineEdit_message.setFont(font)
        self.lineEdit_message.setObjectName("lineEdit_message")
        self.gridLayout_3.addWidget(self.lineEdit_message, 4, 2, 1, 5)
        self.label_contacts = QtWidgets.QLabel(self.tab_chat)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_contacts.setFont(font)
        self.label_contacts.setAlignment(QtCore.Qt.AlignCenter)
        self.label_contacts.setObjectName("label_contacts")
        self.gridLayout_3.addWidget(self.label_contacts, 0, 2, 1, 2)
        self.textBrowser_chat = QtWidgets.QTextBrowser(self.tab_chat)
        self.textBrowser_chat.setObjectName("textBrowser_chat")
        self.gridLayout_3.addWidget(self.textBrowser_chat, 0, 4, 3, 3)
        self.listWidget_contacts = QtWidgets.QListWidget(self.tab_chat)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_contacts.sizePolicy().hasHeightForWidth())
        self.listWidget_contacts.setSizePolicy(sizePolicy)
        self.listWidget_contacts.setObjectName("listWidget_contacts")
        self.gridLayout_3.addWidget(self.listWidget_contacts, 1, 2, 1, 2)
        self.pushButton_send_message = QtWidgets.QPushButton(self.tab_chat)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_send_message.sizePolicy().hasHeightForWidth())
        self.pushButton_send_message.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setKerning(False)
        self.pushButton_send_message.setFont(font)
        self.pushButton_send_message.setObjectName("pushButton_send_message")
        self.gridLayout_3.addWidget(self.pushButton_send_message, 5, 2, 1, 5)
        self.pushButton_add_contact = QtWidgets.QPushButton(self.tab_chat)
        self.pushButton_add_contact.setObjectName("pushButton_add_contact")
        self.gridLayout_3.addWidget(self.pushButton_add_contact, 2, 2, 1, 1)
        self.pushButton_delete_user = QtWidgets.QPushButton(self.tab_chat)
        self.pushButton_delete_user.setObjectName("pushButton_delete_user")
        self.gridLayout_3.addWidget(self.pushButton_delete_user, 2, 3, 1, 1)
        self.tabWidget.addTab(self.tab_chat, "")
        self.tab_settings = QtWidgets.QWidget()
        self.tab_settings.setObjectName("tab_settings")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_settings)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_unlog = QtWidgets.QLabel(self.tab_settings)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_unlog.setFont(font)
        self.label_unlog.setAlignment(QtCore.Qt.AlignCenter)
        self.label_unlog.setObjectName("label_unlog")
        self.gridLayout_2.addWidget(self.label_unlog, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 6, 1, 1, 1)
        self.login_pushbutton = QtWidgets.QPushButton(self.tab_settings)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.login_pushbutton.setFont(font)
        self.login_pushbutton.setObjectName("login_pushbutton")
        self.gridLayout_2.addWidget(self.login_pushbutton, 2, 1, 1, 1)
        self.reg_pushbutton = QtWidgets.QPushButton(self.tab_settings)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.reg_pushbutton.setFont(font)
        self.reg_pushbutton.setObjectName("reg_pushbutton")
        self.gridLayout_2.addWidget(self.reg_pushbutton, 4, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 2, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 4, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 0, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 2, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 4, 2, 1, 1)
        self.pushButton_unlog = QtWidgets.QPushButton(self.tab_settings)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_unlog.setFont(font)
        self.pushButton_unlog.setObjectName("pushButton_unlog")
        self.gridLayout_2.addWidget(self.pushButton_unlog, 5, 1, 1, 1)
        self.tabWidget.addTab(self.tab_settings, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        Client_MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(Client_MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Client_MainWindow)

    def retranslateUi(self, Client_MainWindow):
        _translate = QtCore.QCoreApplication.translate
        Client_MainWindow.setWindowTitle(_translate("Client_MainWindow", "MainWindow"))
        self.label_contacts.setText(_translate("Client_MainWindow", "Контакты"))
        self.pushButton_send_message.setText(_translate("Client_MainWindow", "Отправить сообщение"))
        self.pushButton_add_contact.setText(_translate("Client_MainWindow", "Добавить"))
        self.pushButton_delete_user.setText(_translate("Client_MainWindow", "Удалить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_chat), _translate("Client_MainWindow", "Чат"))
        self.label_unlog.setText(_translate("Client_MainWindow", ""))
        self.login_pushbutton.setText(_translate("Client_MainWindow", "Логин"))
        self.reg_pushbutton.setText(_translate("Client_MainWindow", "Регистрация"))
        self.pushButton_unlog.setText(_translate("Client_MainWindow", "Разлогиниться"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_settings),
                                  _translate("Client_MainWindow", "Подключение"))
