from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Registration(object):
    def setupUi(self, Registration):
        Registration.setObjectName("Registration")
        Registration.resize(400, 600)
        Registration.setMinimumSize(QtCore.QSize(400, 600))
        Registration.setMaximumSize(QtCore.QSize(400, 600))
        self.verticalLayout = QtWidgets.QVBoxLayout(Registration)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label_email = QtWidgets.QLabel(Registration)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_email.setFont(font)
        self.label_email.setAlignment(QtCore.Qt.AlignCenter)
        self.label_email.setObjectName("label_email")
        self.verticalLayout.addWidget(self.label_email)
        self.lineEdit_email = QtWidgets.QLineEdit(Registration)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineEdit_email.setFont(font)
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.verticalLayout.addWidget(self.lineEdit_email)
        self.label_login = QtWidgets.QLabel(Registration)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_login.setFont(font)
        self.label_login.setAlignment(QtCore.Qt.AlignCenter)
        self.label_login.setObjectName("label_login")
        self.verticalLayout.addWidget(self.label_login)
        self.lineEdit_login = QtWidgets.QLineEdit(Registration)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineEdit_login.setFont(font)
        self.lineEdit_login.setObjectName("lineEdit_login")
        self.verticalLayout.addWidget(self.lineEdit_login)
        self.label_password = QtWidgets.QLabel(Registration)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_password.setFont(font)
        self.label_password.setAlignment(QtCore.Qt.AlignCenter)
        self.label_password.setObjectName("label_password")
        self.verticalLayout.addWidget(self.label_password)
        self.lineEdit_password = QtWidgets.QLineEdit(Registration)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineEdit_password.setFont(font)
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.verticalLayout.addWidget(self.lineEdit_password)
        self.label_retype_passeord = QtWidgets.QLabel(Registration)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_retype_passeord.setFont(font)
        self.label_retype_passeord.setAlignment(QtCore.Qt.AlignCenter)
        self.label_retype_passeord.setObjectName("label_retype_passeord")
        self.verticalLayout.addWidget(self.label_retype_passeord)
        self.lineEdit_password_2 = QtWidgets.QLineEdit(Registration)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineEdit_password_2.setFont(font)
        self.lineEdit_password_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password_2.setObjectName("lineEdit_password_2")
        self.verticalLayout.addWidget(self.lineEdit_password_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.pushButton_reg = QtWidgets.QPushButton(Registration)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_reg.setFont(font)
        self.pushButton_reg.setObjectName("pushButton_reg")
        self.verticalLayout.addWidget(self.pushButton_reg)

        self.retranslateUi(Registration)
        QtCore.QMetaObject.connectSlotsByName(Registration)

    def retranslateUi(self, Registration):
        _translate = QtCore.QCoreApplication.translate
        Registration.setWindowTitle(_translate("Registration", "Form"))
        self.label_email.setText(_translate("Registration", "Адрес электронной почты"))
        self.label_login.setText(_translate("Registration", "Логин"))
        self.label_password.setText(_translate("Registration", "Пароль"))
        self.label_retype_passeord.setText(_translate("Registration", "Повторите пароль"))
        self.pushButton_reg.setText(_translate("Registration", "Регистрация"))
