# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(400, 600)
        Login.setMinimumSize(QtCore.QSize(400, 600))
        Login.setMaximumSize(QtCore.QSize(400, 600))
        self.verticalLayout = QtWidgets.QVBoxLayout(Login)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label_login = QtWidgets.QLabel(Login)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_login.setFont(font)
        self.label_login.setAlignment(QtCore.Qt.AlignCenter)
        self.label_login.setObjectName("label_login")
        self.verticalLayout.addWidget(self.label_login)
        self.lineEdit_login = QtWidgets.QLineEdit(Login)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineEdit_login.setFont(font)
        self.lineEdit_login.setObjectName("lineEdit_login")
        self.verticalLayout.addWidget(self.lineEdit_login)
        self.label_password = QtWidgets.QLabel(Login)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_password.setFont(font)
        self.label_password.setAlignment(QtCore.Qt.AlignCenter)
        self.label_password.setObjectName("label_password")
        self.verticalLayout.addWidget(self.label_password)
        self.lineEdit_password = QtWidgets.QLineEdit(Login)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineEdit_password.setFont(font)
        self.lineEdit_password.setAutoFillBackground(False)
        self.lineEdit_password.setInputMethodHints(
            QtCore.Qt.ImhHiddenText | QtCore.Qt.ImhNoAutoUppercase | QtCore.Qt.ImhNoPredictiveText | QtCore.Qt.ImhSensitiveData)
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.verticalLayout.addWidget(self.lineEdit_password)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.pushButton_authorize = QtWidgets.QPushButton(Login)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_authorize.setFont(font)
        self.pushButton_authorize.setObjectName("pushButton_authorize")
        self.verticalLayout.addWidget(self.pushButton_authorize)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Form"))
        self.label_login.setText(_translate("Login", "Логин"))
        self.label_password.setText(_translate("Login", "Пароль"))
        self.pushButton_authorize.setText(_translate("Login", "Авторизоваться"))
